version: '3.8'
services:
  app:
    build: .
    container_name: "core-api-container"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"